let quotes=[
    'The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela',
    'The way to get started is to quit talking and begin doing. -Walt Disney',
    'If life were predictable it would cease to be life, and be without flavor. -Eleanor Roosevelt',
    'If you look at what you have in life, you will always have more.If you look at what you do not have in life, you will never have enough - Oprah Winfrey',
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. -James Cameron",
    "Life is what happens when you're busy making other plans. -John Lennon",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. -Mother Teresa",
    "The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn. -Benjamin Franklin",
    "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart. -Helen Keller",
    "It is during our darkest moments that we must focus to see the light. -Aristotle",
    "Whoever is happy will make others happy too. -Anne Frank",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. -Ralph Waldo Emerson",
    "You will face many defeats in life, but never let yourself be defeated. -Maya Angelou",
    "In the end, it's not the years in your life that count. It's the life in your years. -Abraham Lincoln",
    "Never let the fear of striking out keep you from playing the game. -Babe Ruth",
    "Life is either a daring adventure or nothing at all. -Helen Keller",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. -Thomas A. Edison",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    "However difficult life may seem, there is always something you can do and succeed at",
    "Striving for success without hard work is like trying to harvest where you haven’t planted.",
    "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
    "The only impossible journey is the one you never begin.",
    "In this life we cannot do great things. We can only do small things with great love.",
    "Only a life lived for others is a life worthwhile.",
    "The purpose of our lives is to be happy.",
    "You only live once, but if you do it right, once is enough.",
    "Go confidently in the direction of your dreams! Live the life you've imagined.",
    "Life is really simple, but we insist on making it complicated.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about. -Marilyn Monroe",
    "In three words I can sum up everything I've learned about life: it goes on. -Robert Frost",
    "Success is not final; failure is not fatal: It is the courage to continue that counts. -Winston S. Churchill",
    "Success usually comes to those who are too busy to be looking for it. -Henry David Thoreau",
    "If you really look closely, most overnight successes took a long time. -Steve Jobs",
    "The secret of success is to do the common thing uncommonly well. -John D. Rockefeller Jr.",
    "I find that the harder I work, the more luck I seem to have. -Thomas Jefferson",
    "Don't be distracted by criticism. Remember — the only taste of success some people get is to take a bite out of you.",
    "I never dreamed about success, I worked for it.",
    "Success seems to be connected with action. Successful people keep moving. They make mistakes but they don't quit.",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
    "Try not to become a man of success. Rather become a man of value.",
    "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary",
    "Before anything else, preparation is the key to success.",
    "People who succeed have momentum. The more they succeed, the more they want to succeed and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.",
    "I alone cannot change the world, but I can cast a stone across the water to create many ripples. -Mother Teresa",
    "Nothing is impossible, the word itself says, ‘I'm possible!' -Audrey Hepburn",
    "The champion doesn't do different things, he does things differently",
    "The question isn't who is going to let me; it's who is going to stop me. -Ayn Rand",
    "The only person you are destined to become is the person you decide to be. -Ralph Waldo Emerson",
    "Believe you can and you're halfway there.",
    "Winning isn't everything, but wanting to win is.",
    "Everything you've ever wanted is on the other side of fear.",
    "You may be disappointed if you fail, but you are doomed if you don't try.",
    "Life is 10% what happens to me and 90% of how I react to it.",
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
    "Whatever the mind of man can conceive and believe, it can achieve.",
    "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So, throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover.",
    "If you cannot do great things, do small things in a great way.",
]; 

let div = document.querySelector("#quote");
let c2 = document.querySelector("#card2");
c2.style.display = "none";
let btn=document.querySelector('.btn');
function main(){
let index=Math.floor(Math.random()*quotes.length);
c2.style.display = "block"
div.innerHTML = quotes[index]
}
btn.addEventListener('click', main);